import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Icon, Tag, Btn } from '../components/primitives';
import SiteNav from '../components/SiteNav';
import SiteFooter from '../components/SiteFooter';

const ALL_PROS = {
  photographers: [
    { id: 4,  name: 'Sophie Laurent',  title: 'Wedding Photographer',    studio: 'Laurent Photography',      rating: 5.0, reviews: 318, experience: 9,  sessions: 640,  fee: 350, license: 'NY-PHOTO-041221', specialization: 'Weddings & Portraits',         address: '210 N 8th St, Williamsburg, NY', phone: '+1 (718) 555-1001', email: 'sophie@laurentphoto.com', avail: 'This weekend', insurance: [], specializations: ['Weddings', 'Portraits', 'Engagement Sessions', 'Destination'], img: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&h=300&q=80&auto=format&fit=crop&crop=faces', hero: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=80&auto=format&fit=crop', bio: 'Sophie Laurent has spent nine years documenting weddings across New York and Europe. Her work is known for its timeless elegance and quiet emotional depth — she has a gift for capturing unscripted moments that tell the real story of a day. Sophie works with a small number of couples each year to give every wedding the attention it deserves.', services: ['Full-Day Wedding Coverage', 'Engagement Sessions', 'Bridal Portraits', 'Second Shooter Coordination', 'Album Design', 'Destination Weddings', 'Rehearsal Dinner Coverage'], certifications: ['Professional Photographers of America', 'Wedding Photojournalist Association', 'Adobe Certified Professional', 'WPJA Member'] },
    { id: 5,  name: 'Marcus Cole',     title: 'Event Photographer',      studio: 'Cole Visual',               rating: 4.8, reviews: 204, experience: 7,  sessions: 430,  fee: 220, license: 'NY-PHOTO-053412', specialization: 'Events & Corporate',          address: '88 Atlantic Ave, Brooklyn, NY',   phone: '+1 (718) 555-1002', email: 'marcus@colevisual.com',  avail: 'Next week',   insurance: [], specializations: ['Events', 'Corporate', 'Conferences', 'Headshots'], img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&q=80&auto=format&fit=crop&crop=faces', hero: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&q=80&auto=format&fit=crop', bio: 'Marcus Cole is a Brooklyn-based event photographer with seven years of experience covering everything from intimate gallery openings to large-scale corporate conferences. His editorial background gives his event work a clean, reportage quality that clients consistently describe as both professional and alive.', services: ['Corporate Events', 'Product Launches', 'Conference Coverage', 'Galas & Fundraisers', 'Headshots', 'Team Photos', 'Same-Day Delivery'], certifications: ['Professional Photographers of America', 'Adobe Certified Professional', 'New York Press Photographers Association'] },
    { id: 6,  name: 'Rina Tanaka',     title: 'Portrait Photographer',   studio: 'Tanaka Studio',             rating: 4.9, reviews: 156, experience: 6,  sessions: 390,  fee: 180, license: 'NY-PHOTO-061834', specialization: 'Portraits & Headshots',       address: '55 Greenpoint Ave, Greenpoint, NY', phone: '+1 (718) 555-1003', email: 'rina@tanakastudio.com', avail: 'This week',   insurance: [], specializations: ['Portraits', 'Headshots', 'Personal Branding', 'Actors'], img: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&h=300&q=80&auto=format&fit=crop&crop=faces', hero: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=1200&q=80&auto=format&fit=crop', bio: 'Rina Tanaka runs a boutique portrait studio in Greenpoint that has become a favorite among actors, creatives, and professionals seeking headshots that actually look like them. She approaches every session as a collaborative conversation, helping subjects relax so their personality comes through naturally.', services: ['Professional Headshots', 'Actor Portfolios', 'Personal Branding', 'Family Portraits', 'Maternity Sessions', 'LinkedIn Photos', 'Studio & Outdoor Sessions'], certifications: ['Professional Photographers of America', 'Headshot Crew Member', 'Adobe Certified Professional'] },
    { id: 19, name: 'Luca Ferretti',   title: 'Commercial Photographer', studio: 'Ferretti Creative',         rating: 4.7, reviews: 88,  experience: 11, sessions: 280,  fee: 400, license: 'NY-PHOTO-078921', specialization: 'Commercial & Product',        address: '320 Court St, Brooklyn, NY',      phone: '+1 (718) 555-1004', email: 'luca@ferretticreative.com', avail: 'Next week', insurance: [], specializations: ['Commercial', 'Products', 'E-commerce', 'Advertising'], img: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=300&h=300&q=80&auto=format&fit=crop&crop=faces', hero: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1200&q=80&auto=format&fit=crop', bio: 'Luca Ferretti brings eleven years of commercial photography experience to brands that need imagery that sells. From sleek product flats to full-scale ad campaigns, he works with agencies and direct clients across food, fashion, and tech. His studio in Brooklyn is equipped for full production shoots.', services: ['Product Photography', 'E-commerce Shoots', 'Ad Campaigns', 'Lookbooks', 'Food Photography', 'Architectural Photography', 'Video Production'], certifications: ['Advertising Photographers of America', 'Adobe Certified Expert', 'Canon Professional Services Member'] },
    { id: 20, name: 'Amara Diallo',    title: 'Family Photographer',     studio: 'Diallo Family Photography',rating: 5.0, reviews: 241, experience: 8,  sessions: 510,  fee: 250, license: 'NY-PHOTO-082341', specialization: 'Family & Newborn',           address: '178 7th Ave, Park Slope, NY',     phone: '+1 (718) 555-1005', email: 'amara@diallophotography.com', avail: 'This weekend', insurance: [], specializations: ['Family', 'Newborn', 'Maternity', 'Lifestyle'], img: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=300&h=300&q=80&auto=format&fit=crop&crop=faces', hero: 'https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=1200&q=80&auto=format&fit=crop', bio: 'Amara Diallo is Park Slope\'s most beloved family photographer — known for sessions that feel like play, not a photo shoot. Her calm presence and playful approach put even the most camera-shy toddlers at ease. She specialises in documentary-style family sessions that capture how your family actually lives, laughs, and loves.', services: ['Family Sessions', 'Newborn Photography', 'Maternity', 'Milestone Sessions', 'Sibling Portraits', 'Lifestyle Home Sessions', 'Holiday Cards'], certifications: ['Professional Photographers of America', 'Newborn Posing Safety Certified', 'NAPCP Member'] },
    { id: 21, name: 'Dev Patel',       title: 'Real Estate Photographer',studio: 'Patel Real Estate Imagery',rating: 4.8, reviews: 132, experience: 5,  sessions: 720,  fee: 300, license: 'NY-PHOTO-091237', specialization: 'Interiors & Aerial',         address: '45 Berry St, Williamsburg, NY',   phone: '+1 (718) 555-1006', email: 'dev@patelrealestate.com', avail: 'Tomorrow',    insurance: [], specializations: ['Interiors', 'Aerial', 'Real Estate', 'Architecture'], img: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&h=300&q=80&auto=format&fit=crop&crop=faces', hero: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=80&auto=format&fit=crop', bio: 'Dev Patel shoots some of the most-viewed real estate listings in Brooklyn and Williamsburg. He combines architectural photography with FAA-licensed drone work to give agents and homeowners a complete visual package — from perfectly lit interiors to sweeping aerial views. Fast turnaround, reliable, and obsessively detail-oriented.', services: ['Interior Photography', 'Aerial/Drone Photography', 'Virtual Tours', 'Floor Plan Renders', 'Twilight Shoots', 'Video Walkthroughs', '24h Delivery'], certifications: ['FAA Part 107 Certified', 'PFRE Member', 'Adobe Certified Professional', 'DJI Certified Pilot'] },
    { id: 22, name: 'Chloe Bennett',   title: 'Fashion Photographer',    studio: 'Bennett Studio',            rating: 4.9, reviews: 174, experience: 10, sessions: 320,  fee: 500, license: 'NY-PHOTO-073341', specialization: 'Fashion & Editorial',        address: '56 Wyckoff Ave, Bushwick, NY',    phone: '+1 (718) 555-1007', email: 'chloe@bennettstudio.com', avail: 'Next week',   insurance: [], specializations: ['Fashion', 'Editorial', 'Lookbooks', 'Campaigns'], img: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&h=300&q=80&auto=format&fit=crop&crop=faces', hero: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=1200&q=80&auto=format&fit=crop', bio: 'Chloe Bennett is a fashion and editorial photographer whose work has appeared in Vogue, Harper\'s Bazaar, and numerous independent publications. Her Bushwick studio is a creative hub that attracts designers, models, and brands looking for imagery with a distinctive visual voice. Chloe brings both technical precision and genuine artistic vision to every shoot.', services: ['Editorial Shoots', 'Lookbooks', 'Campaign Photography', 'Model Test Shoots', 'Brand Identity', 'Social Content', 'Studio Rentals'], certifications: ['American Photographic Artists', 'Adobe Certified Expert', 'Canon Professional Services Member', 'Commercial Drone License'] },
    { id: 23, name: 'Noah Williams',   title: 'Sports Photographer',     studio: 'Williams Sports Media',     rating: 4.7, reviews: 99,  experience: 6,  sessions: 210,  fee: 275, license: 'NY-PHOTO-086543', specialization: 'Sports & Action',            address: '740 Flatbush Ave, Brooklyn, NY',  phone: '+1 (718) 555-1008', email: 'noah@williamssports.com', avail: 'Weekends',    insurance: [], specializations: ['Sports', 'Action', 'Athletes', 'Youth Sports'], img: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&h=300&q=80&auto=format&fit=crop&crop=faces', hero: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=1200&q=80&auto=format&fit=crop', bio: 'Noah Williams captures the speed, intensity, and human drama of sport. Whether it\'s a youth soccer league or a professional boxing match, Noah brings the same sharp eye and anticipatory instinct to every frame. His work has been published in ESPN, Sports Illustrated online, and dozens of team publications across the tri-state area.', services: ['Game Day Coverage', 'Team Photography', 'Athlete Portraits', 'Youth Sports', 'Sports Events', 'Action & Training Shoots', 'Video Highlights'], certifications: ['Sports Shooter Academy Alumni', 'NPPA Member', 'Adobe Certified Professional'] },
    { id: 35, name: 'Isla Morrison',   title: 'Food Photographer',       studio: 'Morrison Food Studio',      rating: 4.9, reviews: 113, experience: 7,  sessions: 260,  fee: 320, license: 'NY-PHOTO-094218', specialization: 'Food & Restaurant',          address: '90 Franklin St, Greenpoint, NY',  phone: '+1 (718) 555-1009', email: 'isla@morrisonfood.com', avail: 'This week',   insurance: [], specializations: ['Food', 'Beverage', 'Restaurant', 'Food Styling'], img: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&h=300&q=80&auto=format&fit=crop&crop=faces', hero: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=1200&q=80&auto=format&fit=crop', bio: 'Isla Morrison is a food photographer and stylist who makes dishes look as extraordinary as they taste. She works closely with restaurants, chefs, and food brands across New York to produce imagery for menus, social media, cookbooks, and campaigns. Her Greenpoint studio has a full working kitchen for prepared-food shoots.', services: ['Restaurant Menu Photography', 'Social Media Content', 'Cookbook Shoots', 'Brand Campaigns', 'Recipe Development Photos', 'Beverage Photography', 'Food Styling'], certifications: ['International Food Photography Association', 'Food Styling Certification, ICE', 'Adobe Certified Professional'] },
  ],
  'salon-spa': [
    { id: 7,  name: 'Jade Monroe',     title: 'Master Stylist',          studio: 'Monroe Hair Studio',        rating: 4.9, reviews: 531, experience: 14, sessions: 2800, fee: 95,  license: 'NY-COS-071234', specialization: 'Color & Precision Cuts',      address: '300 Atlantic Ave, Brooklyn, NY',  phone: '+1 (718) 555-2001', email: 'jade@monroehair.com',    avail: 'Tomorrow',    insurance: [], specializations: ['Color', 'Balayage', 'Precision Cuts', 'Keratin'], img: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&q=80&auto=format&fit=crop', bio: 'Jade Monroe has been sculpting and coloring hair in Brooklyn for 14 years. With advanced training from the Vidal Sassoon Academy in London, she is equally at home doing a precision geometric cut or a complex balayage transformation. Her calm, confident approach puts clients at ease and her results keep them coming back.', services: ['Haircut & Style', 'Balayage & Highlights', 'Color Correction', 'Keratin Treatment', 'Scalp Treatment', 'Blowout', 'Bridal Hair'], certifications: ['Vidal Sassoon Academy Graduate', 'Redken Color Certified', 'NY State Cosmetology License', 'Olaplex Certified'] },
    { id: 8,  name: 'Elena Vasquez',   title: 'Esthetician',             studio: 'Glow by Elena',             rating: 4.8, reviews: 289, experience: 8,  sessions: 1200, fee: 80,  license: 'NY-EST-083421', specialization: 'Facials & Skin Care',         address: '125 N 6th St, Williamsburg, NY',  phone: '+1 (718) 555-2002', email: 'elena@glowbyelena.com', avail: 'This week',   insurance: [], specializations: ['Facials', 'Chemical Peels', 'Waxing', 'Skin Care'], img: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=1200&q=80&auto=format&fit=crop', bio: 'Elena Vasquez is a licensed esthetician with eight years of experience helping clients achieve healthy, glowing skin. She takes a holistic approach to skincare — assessing lifestyle, diet, and stress alongside product use. Elena stays current with the latest techniques and only uses clean, results-driven products in her Williamsburg suite.', services: ['Custom Facials', 'Chemical Peels', 'Microdermabrasion', 'LED Light Therapy', 'Brow Shaping', 'Body Waxing', 'Skin Consultations'], certifications: ['NY State Esthetics License', 'Dermalogica Expert', 'PCA Skin Certified', 'Oncology Esthetics Certified'] },
    { id: 9,  name: 'Kira Osei',       title: 'Massage Therapist',       studio: 'Kira Wellness',             rating: 5.0, reviews: 174, experience: 10, sessions: 980,  fee: 110, license: 'NY-MT-094312', specialization: 'Therapeutic Massage',         address: '40 Nassau Ave, Greenpoint, NY',   phone: '+1 (718) 555-2003', email: 'kira@kirawellness.com',  avail: 'Today',       insurance: [], specializations: ['Deep Tissue', 'Swedish', 'Sports Massage', 'Prenatal'], img: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1200&q=80&auto=format&fit=crop', bio: 'Kira Osei is a licensed massage therapist with a decade of practice in therapeutic and wellness massage. She has a rare ability to read tension patterns in the body and target them with precision. Her clients include everyone from desk-bound professionals to competitive athletes. Kira\'s sessions are deeply restorative and her availability is always in demand.', services: ['Swedish Massage', 'Deep Tissue', 'Sports Massage', 'Prenatal Massage', 'Hot Stone Therapy', 'Cupping', 'Lymphatic Drainage'], certifications: ['NY State Massage Therapy License', 'AMTA Member', 'Prenatal Massage Certified', 'Cupping Therapy Certified'] },
    { id: 24, name: 'Tara Nguyen',     title: 'Nail Technician',         studio: 'Tara Nails',                rating: 4.9, reviews: 402, experience: 6,  sessions: 1800, fee: 55,  license: 'NY-NAIL-061289', specialization: 'Gel & Nail Art',             address: '220 5th Ave, Park Slope, NY',     phone: '+1 (718) 555-2004', email: 'tara@taranails.com',     avail: 'Today',       insurance: [], specializations: ['Gel Nails', 'Nail Art', 'Acrylics', 'Dip Powder'], img: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=1200&q=80&auto=format&fit=crop', bio: 'Tara Nguyen has built a cult following in Park Slope for her meticulous gel work and freehand nail art. She trained in nail artistry in Ho Chi Minh City before bringing her skills to New York, and her precision and creativity are unmatched. Tara uses only non-toxic, long-wear formulas and prioritises nail health above all else.', services: ['Gel Manicure', 'Acrylic Extensions', 'Nail Art', 'Nail Repair', 'Pedicure', 'Dip Powder', 'Nail Removal & Care'], certifications: ['NY State Nail Technician License', 'Nail Artist Guild Member', 'CND Shellac Certified', 'Aprés Gel Certified'] },
    { id: 25, name: 'Isabelle Roux',   title: 'Lash Artist',             studio: 'Roux Lash Atelier',         rating: 5.0, reviews: 318, experience: 7,  sessions: 950,  fee: 130, license: 'NY-COS-072341', specialization: 'Lash Extensions & Lifts',    address: '88 Dekalb Ave, Brooklyn, NY',     phone: '+1 (718) 555-2005', email: 'isabelle@rouxlash.com', avail: 'Next week',   insurance: [], specializations: ['Lash Extensions', 'Volume Lashes', 'Lash Lift', 'Brow Lamination'], img: 'https://images.unsplash.com/photo-1583001931096-959e9a1a6223?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1583001931096-959e9a1a6223?w=1200&q=80&auto=format&fit=crop', bio: 'Isabelle Roux trained in Paris before establishing her lash atelier in Brooklyn — and the French attention to detail is evident in every set she creates. She is among the few lash artists in New York certified in the full range of classic, hybrid, volume, and mega-volume techniques. Her waiting list speaks for itself.', services: ['Classic Lash Extensions', 'Hybrid Lashes', 'Volume Lashes', 'Mega Volume', 'Lash Lift & Tint', 'Lash Removal', 'Brow Lamination'], certifications: ['Nouveau Lashes Certified', 'NovaLash Master Stylist', 'NY State Cosmetology License', 'Lash Lift International Certified'] },
    { id: 26, name: 'Priya Kapoor',    title: 'Brow Specialist',         studio: 'Kapoor Brow Studio',        rating: 4.8, reviews: 227, experience: 5,  sessions: 860,  fee: 90,  license: 'NY-COS-083217', specialization: 'Microblading & Brow Design', address: '76 S 4th St, Williamsburg, NY',   phone: '+1 (718) 555-2006', email: 'priya@kapoorbrows.com', avail: 'This week',   insurance: [], specializations: ['Microblading', 'Threading', 'Nano Brows', 'Tinting'], img: 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=1200&q=80&auto=format&fit=crop', bio: 'Priya Kapoor is Williamsburg\'s go-to brow specialist, combining the art of microblading with expert brow mapping to create results that look completely natural. She trained under two of the leading microblading artists in London and brings that precision and patience to every client. Brows are Priya\'s obsession and it shows.', services: ['Microblading', 'Nano Brows', 'Powder/Ombre Brows', 'Brow Lamination', 'Threading', 'Tinting', 'Brow Consultations'], certifications: ['Society of Permanent Cosmetic Professionals', 'SPCP Member', 'NY State License', 'Bloodborne Pathogens Certified'] },
    { id: 27, name: 'Maya Torres',     title: 'Makeup Artist',           studio: 'Torres Beauty',             rating: 4.9, reviews: 183, experience: 9,  sessions: 620,  fee: 150, license: 'NY-COS-069871', specialization: 'Bridal & Editorial Makeup',  address: '112 Knickerbocker Ave, Bushwick, NY', phone: '+1 (718) 555-2007', email: 'maya@torresbeauty.com', avail: 'Weekends',    insurance: [], specializations: ['Bridal Makeup', 'Editorial', 'Airbrush', 'All Skin Tones'], img: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=1200&q=80&auto=format&fit=crop', bio: 'Maya Torres is a New York-based makeup artist with nine years of experience across bridal, editorial, and film work. She is celebrated for her ability to make every client feel beautiful in a way that feels authentic to them — never overdone. Maya works with all skin tones and types, and her bridal clients consistently rave about how flawless their makeup looks all day.', services: ['Bridal Makeup', 'Bridal Trial', 'Bridesmaid Makeup', 'Editorial Makeup', 'Airbrush Application', 'On-Location Services', 'Makeup Lessons'], certifications: ['Make-Up Designory Graduate', 'NY State Cosmetology License', 'IMATS Exhibitor', 'MAC Pro Member'] },
    { id: 28, name: 'Leo Andersen',    title: 'Barber',                  studio: "Leo's Barbershop",          rating: 4.8, reviews: 614, experience: 12, sessions: 4200, fee: 45,  license: 'NY-BARB-052341', specialization: 'Fades & Beard Grooming',      address: '60 Manhattan Ave, Greenpoint, NY',phone: '+1 (718) 555-2008', email: 'leo@leosbarbershop.com', avail: 'Today',       insurance: [], specializations: ['Fades', 'Tapers', 'Beard Trim', 'Hot Towel Shave'], img: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=1200&q=80&auto=format&fit=crop', bio: "Leo Andersen has been cutting hair in Greenpoint for 12 years, building one of the borough's most loyal clienteles. His barbershop is a genuine neighbourhood institution — warm, welcoming, and completely unpretentious. Leo specialises in modern fades and classic taper cuts, and his beard work is exceptional. Walk-ins welcome.", services: ['Haircut', 'Fade', 'Taper Cut', 'Beard Trim & Shape', 'Hot Towel Shave', 'Line Up', 'Kids Cut'], certifications: ['NY State Barber License', 'Andis Educator', 'Wahl Certified', 'Master Barber Guild Member'] },
    { id: 36, name: 'Simone Park',     title: 'Reiki & Wellness',        studio: 'Park Wellness Studio',      rating: 4.9, reviews: 96,  experience: 6,  sessions: 380,  fee: 120, license: 'NY-WELL-087123', specialization: 'Reiki & Holistic Wellness',  address: '410 7th Ave, Park Slope, NY',     phone: '+1 (718) 555-2009', email: 'simone@parkwellness.com', avail: 'This week',  insurance: [], specializations: ['Reiki', 'Sound Healing', 'Breathwork', 'Meditation'], img: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1200&q=80&auto=format&fit=crop', bio: 'Simone Park is a Reiki master and holistic wellness practitioner who helps clients navigate stress, anxiety, and burnout through energy healing and mindfulness practices. Her Park Slope studio is a serene space designed to facilitate genuine rest and renewal. Simone integrates Reiki, sound healing, and breathwork into personalised sessions.', services: ['Reiki Healing', 'Sound Bath', 'Breathwork Sessions', 'Meditation Coaching', 'Chakra Balancing', 'Crystal Therapy', 'Wellness Consultations'], certifications: ['Usui Reiki Master Certification', 'International Association of Reiki Professionals', 'Sound Healing Academy Graduate', 'Mindfulness-Based Stress Reduction (MBSR)'] },
  ],
  'home-services': [
    { id: 40, name: 'Carlos Mendez',      title: 'Licensed Plumber',              studio: 'Mendez Plumbing',             rating: 4.9, reviews: 312, experience: 12, sessions: 890,  fee: 95,  license: 'NY-PLUMB-041221', specialization: 'Plumbing & Emergency Repairs',    address: '200 Atlantic Ave, Brooklyn, NY',  phone: '+1 (718) 555-6001', email: 'carlos@mendezplumbing.com',  avail: 'Today',       insurance: [], specializations: ['Plumbing', 'Emergency', 'Pipe Repair', 'Water Heaters'], img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80&auto=format&fit=crop', bio: 'Carlos Mendez is a licensed master plumber with 12 years of experience across Brooklyn and the wider New York area. He handles everything from a leaking faucet to a full bathroom rough-in, and his emergency response time is among the fastest in the borough. Carlos is known for transparent pricing, zero upselling, and work that holds up.', services: ['Emergency Repairs', 'Pipe Replacement', 'Water Heater Install', 'Drain Cleaning', 'Bathroom Plumbing', 'Kitchen Plumbing', 'Leak Detection'], certifications: ['NY State Master Plumber License', 'NYC DOB Licensed', 'EPA WaterSense Certified', 'PHCC Member'] },
    { id: 41, name: 'Mike Torres',        title: 'Master Electrician',            studio: 'Torres Electric',             rating: 4.8, reviews: 198, experience: 15, sessions: 740,  fee: 110, license: 'NY-ELEC-053412', specialization: 'Residential & Commercial Wiring',address: '88 Bedford Ave, Williamsburg, NY', phone: '+1 (718) 555-6002', email: 'mike@torreselectric.com',    avail: 'Tomorrow',    insurance: [], specializations: ['Electrical', 'Rewiring', 'Panel Upgrade', 'EV Chargers'], img: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&q=80&auto=format&fit=crop', bio: 'Mike Torres has 15 years of electrical experience in New York residential and commercial spaces. He specializes in safe, code-compliant electrical work — from panel upgrades and full rewiring to EV charger installations and smart home systems. His background in commercial construction means he approaches every job with the rigor and precision it deserves.', services: ['Panel Upgrades', 'Full Rewiring', 'EV Charger Install', 'Outlet & Switch Work', 'Lighting Design', 'Smart Home Wiring', 'Safety Inspections'], certifications: ['NY State Master Electrician License', 'NYC DOB Licensed', 'IBEW Member', 'NECA Certified'] },
    { id: 42, name: 'Sunshine Cleaners',  title: 'Residential Cleaning Co.',      studio: 'Sunshine Cleaning NYC',       rating: 5.0, reviews: 541, experience: 8,  sessions: 2400, fee: 80,  license: 'NYC-BUS-061834', specialization: 'Deep Clean & Regular Maintenance', address: '30 Nassau Ave, Greenpoint, NY',    phone: '+1 (718) 555-6003', email: 'book@sunshinecleaners.nyc', avail: 'This week',   insurance: [], specializations: ['Deep Clean', 'Move In/Out', 'Regular Cleaning', 'Eco-Friendly'], img: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200&q=80&auto=format&fit=crop', bio: 'Sunshine Cleaning NYC has been transforming Brooklyn homes for eight years. The team of six fully insured and background-checked cleaners use eco-friendly, fragrance-free products throughout. From one-off deep cleans to weekly maintenance, they are consistently the highest-rated cleaning service in Greenpoint and surrounding neighbourhoods.', services: ['Standard Clean', 'Deep Clean', 'Move-In/Out Clean', 'Post-Renovation Clean', 'Weekly Maintenance', 'One-Time Visit', 'Eco Package'], certifications: ['NYC Licensed & Insured', 'ISSA Member', 'Green Seal Certified Products', 'Background-Checked Team'] },
    { id: 43, name: 'Ray Fitzgerald',     title: 'Painter & Decorator',           studio: 'Fitzgerald Painting Co.',     rating: 4.8, reviews: 174, experience: 10, sessions: 560,  fee: 75,  license: 'NYC-CON-078921', specialization: 'Interior & Exterior Painting',   address: '150 7th Ave, Park Slope, NY',     phone: '+1 (718) 555-6004', email: 'ray@fitzgeraldpainting.com', avail: 'Next week',   insurance: [], specializations: ['Interior Painting', 'Exterior', 'Wallpaper', 'Faux Finish'], img: 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=1200&q=80&auto=format&fit=crop', bio: 'Ray Fitzgerald has been painting homes in Park Slope and across Brooklyn for a decade. He takes the time to properly prepare every surface — which is why his finishes last. Ray works with a small, dedicated crew and personally oversees every job. He is meticulous about color consultation, surface prep, and leaving your home cleaner than he found it.', services: ['Interior Painting', 'Exterior Painting', 'Cabinet Painting', 'Wallpaper Hanging', 'Drywall Repair', 'Staining & Varnishing', 'Color Consultation'], certifications: ['NYC Licensed Contractor', 'EPA Lead-Safe Certified', 'Sherwin-Williams Certified Applicator', 'PDCA Member'] },
    { id: 44, name: 'BK Carpentry Co.',   title: 'Custom Carpentry & Joinery',    studio: 'BK Carpentry',                rating: 4.9, reviews: 230, experience: 14, sessions: 480,  fee: 120, license: 'NYC-CON-082341', specialization: 'Built-ins & Custom Furniture',   address: '280 Court St, Brooklyn, NY',      phone: '+1 (718) 555-6005', email: 'info@bkcarpentry.com',       avail: 'This week',   insurance: [], specializations: ['Carpentry', 'Built-ins', 'Custom Furniture', 'Trim Work'], img: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=1200&q=80&auto=format&fit=crop', bio: 'BK Carpentry has been crafting custom built-ins, furniture, and architectural millwork in Brooklyn homes for 14 years. Owner and lead carpenter Darius Webb brings a furniture-maker\'s precision to every project — whether it\'s a floor-to-ceiling bookcase, a kitchen island, or a full set of closets. His work has been featured in Brownstoner and Brooklyn Magazine.', services: ['Custom Built-ins', 'Bookshelves & Cabinets', 'Custom Furniture', 'Closet Systems', 'Crown & Base Molding', 'Wood Flooring', 'Deck Building'], certifications: ['NYC Licensed Contractor', 'Woodworkers Guild Member', 'EPA Lead-Safe Certified', 'NARI Member'] },
    { id: 45, name: 'CoolAir HVAC',       title: 'HVAC Install & Repair',         studio: 'CoolAir NYC',                 rating: 4.7, reviews: 147, experience: 11, sessions: 620,  fee: 130, license: 'NYC-HVAC-091237', specialization: 'AC, Heating & Ventilation',      address: '90 Wyckoff Ave, Bushwick, NY',    phone: '+1 (718) 555-6006', email: 'service@coolaircnyc.com',    avail: 'Today',       insurance: [], specializations: ['HVAC', 'AC Installation', 'Furnace Repair', 'Ductwork'], img: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=1200&q=80&auto=format&fit=crop', bio: 'CoolAir NYC provides fast, reliable HVAC installation, repair, and maintenance across Brooklyn. The team of EPA-certified technicians handles everything from mini-split installations to full central air conversions and furnace replacements. They offer same-day service for breakdowns and honest assessments — they will tell you if a repair makes more sense than a replacement.', services: ['AC Installation', 'Furnace Repair', 'Mini-Split Systems', 'Duct Cleaning', 'Annual Maintenance', 'Emergency Repair', 'Smart Thermostat Install'], certifications: ['EPA 608 Certified', 'NATE Certified Technician', 'NYC DOB Registered', 'ACCA Member'] },
    { id: 46, name: 'GreenThumb NYC',     title: 'Landscaping & Gardening',       studio: 'GreenThumb Landscaping',      rating: 4.9, reviews: 189, experience: 9,  sessions: 510,  fee: 90,  license: 'NYC-LAN-073341', specialization: 'Garden Design & Maintenance',    address: '55 Grand St, Williamsburg, NY',   phone: '+1 (718) 555-6007', email: 'hello@greenthumbnyc.com',    avail: 'This week',   insurance: [], specializations: ['Landscaping', 'Garden Design', 'Lawn Care', 'Planting'], img: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200&q=80&auto=format&fit=crop', bio: 'GreenThumb NYC designs and maintains beautiful outdoor spaces for Brooklyn homeowners, businesses, and co-ops. Their landscape design team combines horticultural knowledge with genuine aesthetic sensibility to create gardens that thrive in New York\'s urban environment. From seasonal planting to full garden redesigns, they treat every outdoor space as a creative project worth caring about.', services: ['Garden Design', 'Seasonal Planting', 'Lawn Care', 'Hedge Trimming', 'Tree Pruning', 'Irrigation Systems', 'Rooftop Gardens'], certifications: ['NALP Certified Landscape Professional', 'NYC Licensed Contractor', 'ISA Certified Arborist', 'NY Horticultural Society Member'] },
    { id: 47, name: 'Boro Movers',        title: 'Local Moving Service',          studio: 'Boro Movers NYC',             rating: 4.8, reviews: 403, experience: 7,  sessions: 1800, fee: 150, license: 'NYSDOT-071234', specialization: 'Local & Long-Distance Moving',   address: '600 Flatbush Ave, Brooklyn, NY',  phone: '+1 (718) 555-6008', email: 'move@bormovers.nyc',         avail: 'This weekend', insurance: [], specializations: ['Moving', 'Packing', 'Storage', 'Piano Moving'], img: 'https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=1200&q=80&auto=format&fit=crop', bio: 'Boro Movers is Brooklyn\'s most consistently reviewed moving company — and for good reason. Their team of uniformed, background-checked movers treats your belongings with the same care they would their own. Full packing services, furniture disassembly and reassembly, and secure short-term storage are all available. No hidden fees, ever.', services: ['Local Moving', 'Long-Distance Moving', 'Full Packing Service', 'Furniture Assembly', 'Storage Solutions', 'Piano Moving', 'Office Relocations'], certifications: ['NYSDOT Licensed Mover', 'AMSA ProMover', 'Fully Insured & Bonded', 'BBB Accredited'] },
    { id: 48, name: 'Fix-It Fast',        title: 'General Handyman',              studio: 'Fix-It Fast NYC',             rating: 4.7, reviews: 267, experience: 8,  sessions: 1100, fee: 70,  license: 'NYC-GEN-086543', specialization: 'General Repairs & Maintenance',  address: '20 Calyer St, Greenpoint, NY',    phone: '+1 (718) 555-6009', email: 'book@fixitfastnyc.com',      avail: 'Today',       insurance: [], specializations: ['Handyman', 'Plumbing', 'Electrical', 'Assembly'], img: 'https://images.unsplash.com/photo-1574361767743-23bd9b80e3ee?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1574361767743-23bd9b80e3ee?w=1200&q=80&auto=format&fit=crop', bio: 'Fix-It Fast is Greenpoint\'s go-to handyman service for everything from a stuck door to a full bathroom retile. Owner Marcus James has eight years of experience across plumbing, electrical, carpentry, and general repairs — and he is honest about what falls within his scope and when a specialist is needed. Same-day and next-day availability most weeks.', services: ['General Repairs', 'Furniture Assembly', 'TV Mounting', 'Door & Lock Repair', 'Minor Plumbing', 'Tile Work', 'Drywall Patching'], certifications: ['NYC Licensed & Insured', 'HomeAdvisor Certified', 'Background Checked', 'Angi Top Pro 2024'] },
  ],
  'professional-service': [
    { id: 50, name: 'Priya Sharma, Esq.', title: 'Business & Contract Attorney',  studio: 'Sharma Law Group',            rating: 4.9, reviews: 208, experience: 11, sessions: 640,  fee: 250, license: 'NY-BAR-041221', specialization: 'Business Law & Contracts',        address: '100 Montague St, Brooklyn, NY',   phone: '+1 (718) 555-7001', email: 'priya@sharmalaw.com',        avail: 'This week',   insurance: [], specializations: ['Business Law', 'Contracts', 'Startups', 'Employment'], img: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&h=300&q=80&auto=format&fit=crop&crop=faces', hero: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&q=80&auto=format&fit=crop', bio: 'Priya Sharma is a Brooklyn Heights attorney specializing in business formation, commercial contracts, and employment law for startups and small businesses. After a decade at a Manhattan firm, she launched her boutique practice to give founders and entrepreneurs the kind of responsive, personal legal service that larger firms rarely offer. She speaks plainly, bills fairly, and picks up the phone.', services: ['Business Formation', 'Contract Drafting & Review', 'Employment Agreements', 'Founder Agreements', 'NDA & IP Agreements', 'Lease Review', 'Legal Consultations'], certifications: ['NY State Bar Association', 'Brooklyn Bar Association', 'Volunteer Lawyers for the Arts', 'SCORE Mentor'] },
    { id: 51, name: 'Marcus Webb, CPA',   title: 'Certified Public Accountant',   studio: 'Webb Accounting & Tax',       rating: 4.9, reviews: 341, experience: 14, sessions: 1200, fee: 180, license: 'NY-CPA-053412', specialization: 'Tax Strategy & Small Business',   address: '200 N 7th St, Williamsburg, NY',  phone: '+1 (718) 555-7002', email: 'marcus@webbaccounting.com', avail: 'Next week',   insurance: [], specializations: ['Tax Planning', 'Accounting', 'Small Business', 'Freelancers'], img: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&h=300&q=80&auto=format&fit=crop&crop=faces', hero: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&q=80&auto=format&fit=crop', bio: 'Marcus Webb has been helping freelancers, small business owners, and creatives navigate their finances for 14 years. His practice covers everything from annual tax filing and bookkeeping to proactive tax strategy — the kind of planning that saves real money. Marcus has a particular affinity for working with musicians, artists, and independent contractors who find accounting intimidating.', services: ['Tax Preparation & Filing', 'Bookkeeping', 'Payroll', 'Business Tax Strategy', 'IRS Representation', 'Financial Planning', 'QuickBooks Setup'], certifications: ['NY State CPA License', 'AICPA Member', 'QuickBooks ProAdvisor', 'Enrolled Agent'] },
    { id: 52, name: 'Lin & Associates',   title: 'Business Strategy Consulting',  studio: 'Lin & Associates',            rating: 4.8, reviews: 126, experience: 12, sessions: 380,  fee: 200, license: 'NYC-BUS-061834', specialization: 'Growth Strategy & Operations',    address: '65 Greenpoint Ave, Greenpoint, NY', phone: '+1 (718) 555-7003', email: 'hello@linassociates.com',   avail: 'This week',   insurance: [], specializations: ['Strategy', 'Operations', 'Finance', 'Scaling'], img: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=300&h=300&q=80&auto=format&fit=crop&crop=faces', hero: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=1200&q=80&auto=format&fit=crop', bio: 'Lin & Associates is a boutique business strategy consultancy working with growth-stage companies across New York. Founded by Jennifer Lin after a decade at McKinsey, the firm brings enterprise-level strategic rigour to businesses that are too small for the big firms but serious about scaling. Engagements range from one-off workshops to ongoing fractional COO arrangements.', services: ['Growth Strategy', 'Operations Audit', 'Financial Modelling', 'Market Entry', 'Team Structuring', 'Fractional COO', 'Board Advisory'], certifications: ['Harvard Business School Executive', 'CMC – Certified Management Consultant', 'PMI Certified', 'SCORE Mentor'] },
    { id: 53, name: 'Omar Khalil',        title: 'Digital Marketing Consultant',  studio: 'Khalil Digital',              rating: 4.7, reviews: 183, experience: 8,  sessions: 490,  fee: 120, license: 'NYC-BUS-078921', specialization: 'SEO, Paid Ads & Content',         address: '410 5th Ave, Park Slope, NY',     phone: '+1 (718) 555-7004', email: 'omar@khalildigital.com',    avail: 'Today',       insurance: [], specializations: ['SEO', 'Google Ads', 'Social Media', 'Content Strategy'], img: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&h=300&q=80&auto=format&fit=crop&crop=faces', hero: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80&auto=format&fit=crop', bio: 'Omar Khalil is a Brooklyn-based digital marketing consultant with eight years of experience growing brands through search, paid media, and content strategy. He has worked with everything from direct-to-consumer e-commerce brands to local professional service firms — and he brings the same data-driven rigour to both. Omar is particularly strong in SEO and Google Ads, where he consistently delivers measurable ROI.', services: ['SEO Strategy & Implementation', 'Google & Meta Ads', 'Content Marketing', 'Email Marketing', 'Analytics & Reporting', 'Social Media Strategy', 'Brand Positioning'], certifications: ['Google Ads Certified', 'Meta Blueprint Certified', 'HubSpot Content Marketing', 'Google Analytics 4 Certified'] },
    { id: 54, name: 'Studio Axis',        title: 'Brand & UX Design Agency',     studio: 'Studio Axis',                 rating: 5.0, reviews: 97,  experience: 7,  sessions: 210,  fee: 160, license: 'NYC-BUS-082341', specialization: 'Brand Identity & Product Design',  address: '320 Atlantic Ave, Brooklyn, NY',  phone: '+1 (718) 555-7005', email: 'hello@studioaxis.co',       avail: 'Next week',   insurance: [], specializations: ['Branding', 'UX Design', 'Web Design', 'Product'], img: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1558655146-d09347e92766?w=1200&q=80&auto=format&fit=crop', bio: 'Studio Axis is a brand and experience design studio working with startups, cultural institutions, and consumer brands. The team of four designers approaches every project with equal care for visual craft and strategic clarity — creating brands that look extraordinary and actually perform. From early-stage identity work to complex product interfaces, their portfolio is broad and consistently excellent.', services: ['Brand Identity', 'Visual Design', 'UX/UI Design', 'Website Design', 'Design Systems', 'Art Direction', 'Print & Packaging'], certifications: ['AIGA Member', 'Google UX Design Certificate', 'Figma Education Partner', 'Webby Awards Honoree'] },
    { id: 55, name: 'Anika Patel, CFP',   title: 'Certified Financial Planner',   studio: 'Patel Financial Planning',    rating: 4.9, reviews: 152, experience: 9,  sessions: 430,  fee: 220, license: 'CFP-091237', specialization: 'Personal Finance & Investment',    address: '78 Grand St, Williamsburg, NY',   phone: '+1 (718) 555-7006', email: 'anika@patelfinancial.com',  avail: 'This week',   insurance: [], specializations: ['Financial Planning', 'Investment', 'Retirement', 'Tax Strategy'], img: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&h=300&q=80&auto=format&fit=crop&crop=faces', hero: 'https://images.unsplash.com/photo-1579621970590-9d152b5cb47b?w=1200&q=80&auto=format&fit=crop', bio: 'Anika Patel is a Certified Financial Planner helping individuals and families in Brooklyn make confident decisions about their money. She works with clients at every life stage — from building a first investment portfolio to planning for retirement and estate considerations. Her approach is non-judgmental, jargon-free, and focused on what actually matters to each client.', services: ['Financial Planning', 'Investment Management', 'Retirement Planning', 'Tax-Efficient Investing', 'Estate Planning Basics', 'Budget & Debt Strategy', 'Financial Check-Ups'], certifications: ['CFP® Certified Financial Planner', 'CFA Level II Candidate', 'NAPFA Member', 'FPA Member'] },
    { id: 56, name: 'TalentBridge HR',    title: 'HR & Recruiting Consultancy',   studio: 'TalentBridge',                rating: 4.8, reviews: 74,  experience: 10, sessions: 290,  fee: 140, license: 'NYC-BUS-073341', specialization: 'HR Strategy & Talent Acquisition', address: '44 Wyckoff Ave, Bushwick, NY',    phone: '+1 (718) 555-7007', email: 'hi@talentbridgenyc.com',    avail: 'This week',   insurance: [], specializations: ['HR', 'Recruiting', 'People Ops', 'Culture'], img: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&q=80&auto=format&fit=crop', bio: 'TalentBridge helps growing companies build great teams and HR foundations. Whether you\'re hiring your first employees, building out your people operations, or navigating a tricky HR situation, founder Sarah Cho brings a decade of in-house experience at venture-backed startups to bear. She operates as a fractional HR partner — giving you the expertise of a seasoned people leader without the full-time cost.', services: ['Talent Acquisition', 'Job Description Writing', 'Interview Process Design', 'Onboarding Systems', 'HR Policy Creation', 'Culture & Engagement', 'Fractional HR Partnership'], certifications: ['SHRM-CP Certified', 'PHR Certified', 'LinkedIn Recruiter Certified', 'HRCI Member'] },
    { id: 57, name: 'CodeNest IT',        title: 'IT Support & Managed Services', studio: 'CodeNest IT Services',        rating: 4.8, reviews: 211, experience: 12, sessions: 780,  fee: 100, license: 'NYC-BUS-086543', specialization: 'IT Support & Cybersecurity',       address: '80 Franklin St, Greenpoint, NY',  phone: '+1 (718) 555-7008', email: 'support@codenestit.com',    avail: 'Today',       insurance: [], specializations: ['IT Support', 'Cybersecurity', 'Cloud', 'Managed Services'], img: 'https://images.unsplash.com/photo-1571171637578-41bc2dd41cd2?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80&auto=format&fit=crop', bio: 'CodeNest provides responsive, transparent IT support and managed services to small and medium-sized businesses across Brooklyn. The team handles everything from day-to-day helpdesk support and device management to cybersecurity assessments and cloud migrations. They speak in plain English, respond quickly, and have a genuine understanding of what non-technical business owners need from their technology.', services: ['IT Helpdesk', 'Network Setup & Management', 'Cybersecurity', 'Cloud Migration', 'Data Backup', 'Device Management', 'IT Strategy'], certifications: ['CompTIA Security+', 'AWS Solutions Architect', 'Microsoft 365 Certified', 'Cisco CCNA'] },
    { id: 58, name: 'Reyes Notary',       title: 'Notary & Document Services',    studio: 'Reyes Notary Services',       rating: 4.9, reviews: 488, experience: 6,  sessions: 2100, fee: 50,  license: 'NY-NOT-094218', specialization: 'Notarization & Apostille',         address: '700 Flatbush Ave, Brooklyn, NY',  phone: '+1 (718) 555-7009', email: 'luis@reyesnotary.com',      avail: 'Today',       insurance: [], specializations: ['Notary', 'Apostille', 'Mobile Notary', 'Loan Signing'], img: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=80&auto=format&fit=crop', bio: 'Luis Reyes is one of Brooklyn\'s most in-demand notaries — known for fast availability, mobile service across all five boroughs, and meticulous accuracy. He handles everything from single-document notarizations to complex apostille packages for international use. Loan signings, real estate closings, affidavits, and power of attorney are all within his regular scope of work.', services: ['Document Notarization', 'Apostille Certification', 'Loan Document Signing', 'Real Estate Closings', 'Affidavits', 'Power of Attorney', 'Mobile Notary'], certifications: ['NY State Commissioned Notary', 'NNA Certified Notary Signing Agent', 'Loan Signing System Certified', 'Background Screened'] },
  ],
  restaurants: [
    { id: 10, name: 'Osteria Nolita',  title: 'Italian · Fine Dining',   studio: 'Osteria Nolita',            rating: 4.9, reviews: 892,  experience: 8,  sessions: 0, fee: 65,  license: 'NYC-REST-041221', specialization: 'Southern Italian Cuisine',   address: '88 Smith St, Brooklyn, NY',       phone: '+1 (718) 555-3001', email: 'reservations@osterianolita.com', avail: 'Reservations open', insurance: [], specializations: ['Italian', 'Fine Dining', 'Wine Bar', 'Private Dining'], img: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&q=80&auto=format&fit=crop', bio: 'Osteria Nolita brings the warmth of a Southern Italian trattoria to the heart of Brooklyn. Chef Marco Ricci trained in Naples before moving to New York, and his menu is a love letter to the cucina of his childhood — handmade pasta, wood-fired proteins, and an exceptional natural wine list. The space is intimate, candlelit, and consistently one of the most romantic rooms in the borough.', services: ['Dinner Service', 'Private Dining', 'Wine Pairing Menus', 'Chef\'s Tasting Menu', 'Catering', 'Wine Bar', 'Brunch (Weekend)'], certifications: ['NYC Health Dept A Rating', 'James Beard Semifinalist 2024', 'Michelin Bib Gourmand', 'Wine Spectator Award of Excellence'] },
    { id: 11, name: 'Sōra Ramen',      title: 'Japanese · Casual',       studio: 'Sōra Ramen',                rating: 4.8, reviews: 1204, experience: 5,  sessions: 0, fee: 22,  license: 'NYC-REST-053412', specialization: 'Tonkotsu & Shoyu Ramen',     address: '310 Bedford Ave, Williamsburg, NY',phone: '+1 (718) 555-3002', email: 'hello@soraramen.com',           avail: 'Walk-ins welcome', insurance: [], specializations: ['Ramen', 'Izakaya', 'Japanese', 'Takeout'], img: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=1200&q=80&auto=format&fit=crop', bio: 'Sōra Ramen has become Williamsburg\'s definitive ramen destination since opening five years ago. The broth is simmered for 18 hours, the noodles are made fresh daily, and the chashu pork is slow-braised to melt-in-your-mouth perfection. The izakaya-style small plates are equally worth ordering — especially the karaage and the gyoza.', services: ['Dine In', 'Takeout', 'Delivery', 'Izakaya Menu', 'Happy Hour', 'Private Events', 'Catering'], certifications: ['NYC Health Dept A Rating', 'Eater NY Best Ramen 2023', 'Time Out NYC Editors Pick'] },
    { id: 12, name: 'Casa Verde',      title: 'Mexican · Brunch',        studio: 'Casa Verde',                rating: 4.7, reviews: 643,  experience: 4,  sessions: 0, fee: 30,  license: 'NYC-REST-061834', specialization: 'Modern Mexican & Brunch',    address: '70 Nassau Ave, Greenpoint, NY',   phone: '+1 (718) 555-3003', email: 'hola@casaverdebrooklyn.com',    avail: 'Walk-ins welcome', insurance: [], specializations: ['Mexican', 'Brunch', 'Tacos', 'Cocktails'], img: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80&auto=format&fit=crop', bio: 'Casa Verde is Greenpoint\'s most beloved weekend destination, known for a brunch menu that combines classic Mexican flavours with unexpected twists. The margaritas are made with fresh-pressed juice and the tacos are extraordinary. Their weekday lunch and dinner menus are quieter-kept secrets equally worth discovering.', services: ['Brunch', 'Lunch', 'Dinner', 'Takeout', 'Delivery', 'Catering', 'Private Events'], certifications: ['NYC Health Dept A Rating', 'Zagat Rated', 'Infatuation Top Pick'] },
    { id: 29, name: 'The Ember Room',  title: 'American · Steakhouse',   studio: 'The Ember Room',            rating: 4.9, reviews: 741,  experience: 6,  sessions: 0, fee: 85,  license: 'NYC-REST-078921', specialization: 'Wood-Fire Grill & Cocktails',address: '150 Atlantic Ave, Brooklyn, NY',  phone: '+1 (718) 555-3004', email: 'book@theemberroom.com',         avail: 'Reservations open', insurance: [], specializations: ['Steakhouse', 'Wood-Fire', 'Cocktails', 'Private Events'], img: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1200&q=80&auto=format&fit=crop', bio: 'The Ember Room is Brooklyn\'s premier wood-fire steakhouse — a bold, dimly-lit space where every cut is selected from small American farms and cooked over live ember. The cocktail programme is equally serious, and the private dining room has hosted everything from corporate dinners to marriage proposals. Reservations are strongly recommended.', services: ['Dinner Service', 'Private Dining', 'Cocktail Bar', 'Weekend Brunch', 'Corporate Events', 'Wine Cellar Tastings', 'Chef\'s Table'], certifications: ['NYC Health Dept A Rating', 'Wine Spectator Award', 'New York Times 2 Stars', 'James Beard Long List 2025'] },
    { id: 30, name: 'Mango & Lime',    title: 'Caribbean · Casual',      studio: 'Mango & Lime',              rating: 4.8, reviews: 529,  experience: 7,  sessions: 0, fee: 28,  license: 'NYC-REST-082341', specialization: 'Caribbean Soul Food',        address: '900 Flatbush Ave, Flatbush, NY',  phone: '+1 (718) 555-3005', email: 'hello@mangoandlime.com',        avail: 'Walk-ins welcome', insurance: [], specializations: ['Caribbean', 'Soul Food', 'Vegan', 'Catering'], img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=80&auto=format&fit=crop', bio: 'Mango & Lime brings the vibrant soul food traditions of the Caribbean — Jamaica, Trinidad, and Barbados — to the heart of Flatbush. Family-owned and fiercely community-focused, the menu rotates seasonally and always includes outstanding vegan options. The jerk chicken is legendary in the neighbourhood, and the rum punch is dangerously good.', services: ['Dine In', 'Takeout', 'Delivery', 'Catering', 'Event Space', 'Sunday Brunch', 'Vegan Menu'], certifications: ['NYC Health Dept A Rating', 'Eater NY Neighbourhood Gem', 'Best of Brooklyn 2024'] },
    { id: 31, name: 'Tulum Kitchen',   title: 'Mexican · Fine Dining',   studio: 'Tulum Kitchen',             rating: 5.0, reviews: 418,  experience: 3,  sessions: 0, fee: 95,  license: 'NYC-REST-091237', specialization: 'Tasting Menu & Mezcal Bar', address: '55 Wythe Ave, Williamsburg, NY',  phone: '+1 (718) 555-3006', email: 'dine@tulumkitchen.com',         avail: 'Reservations open', insurance: [], specializations: ['Fine Dining', 'Tasting Menu', 'Mexican', 'Mezcal'], img: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=1200&q=80&auto=format&fit=crop', bio: 'Tulum Kitchen elevated Mexican fine dining in Williamsburg from the moment it opened. Chef Ana Reyes draws on her Oaxacan roots and Michelin-kitchen training to produce a tasting menu that surprises and delights — bold flavours, unexpected techniques, beautiful plating. The mezcal bar alone is worth the trip.', services: ['Tasting Menu', 'À La Carte Dinner', 'Mezcal Bar', 'Private Events', 'Chef\'s Table', 'Weekend Brunch', 'Cocktail Pairing'], certifications: ['NYC Health Dept A Rating', 'Michelin Star 2024', 'New York Times 3 Stars', 'James Beard Award Nominee'] },
    { id: 32, name: 'Spice Route',     title: 'Indian · Modern',         studio: 'Spice Route',               rating: 4.8, reviews: 387,  experience: 9,  sessions: 0, fee: 40,  license: 'NYC-REST-073341', specialization: 'Modern Indian Cuisine',      address: '340 5th Ave, Park Slope, NY',     phone: '+1 (718) 555-3007', email: 'eat@spiceroute.nyc',            avail: 'Walk-ins welcome', insurance: [], specializations: ['Indian', 'Modern', 'Vegetarian', 'Catering'], img: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=1200&q=80&auto=format&fit=crop', bio: 'Spice Route is Park Slope\'s most celebrated Indian restaurant — a sophisticated space where traditional recipes meet modern plating and seasonal New York produce. The menu spans regional India with exceptional depth: Keralan seafood, Punjabi slow-braised meats, and Delhi street food given a refined treatment. The vegetarian selection is outstanding.', services: ['Dine In', 'Takeout', 'Delivery', 'Private Dining', 'Catering', 'Vegetarian Menu', 'Weekend Brunch'], certifications: ['NYC Health Dept A Rating', 'Michelin Bib Gourmand', 'Time Out NY Top Indian 2024', 'Zagat 27/30'] },
    { id: 33, name: 'Le Petit Bistro', title: 'French · Café',           studio: 'Le Petit Bistro',           rating: 4.9, reviews: 602,  experience: 11, sessions: 0, fee: 35,  license: 'NYC-REST-086543', specialization: 'French Café & Brunch',      address: '112 Franklin St, Greenpoint, NY', phone: '+1 (718) 555-3008', email: 'bonjour@lepetitbistro.nyc',     avail: 'Walk-ins welcome', insurance: [], specializations: ['French', 'Brunch', 'Wine Bar', 'Breakfast'], img: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80&auto=format&fit=crop', bio: 'Le Petit Bistro is a genuine piece of Paris transplanted to Greenpoint — tin ceilings, bentwood chairs, and a chalkboard menu that changes with the seasons. The croissants are made fresh every morning, the steak frites are legendary, and the wine list is thoughtfully chosen and fairly priced. It\'s the neighbourhood restaurant everyone wishes they had.', services: ['Breakfast', 'Brunch', 'Lunch', 'Dinner', 'Wine Bar', 'Catering', 'Private Events'], certifications: ['NYC Health Dept A Rating', 'Michelin Bib Gourmand', 'New York Times Critic\'s Pick', 'Best Brunch Brooklyn 2024'] },
    { id: 34, name: 'Nori & Co.',      title: 'Japanese · Sushi',        studio: 'Nori & Co.',                rating: 5.0, reviews: 511,  experience: 6,  sessions: 0, fee: 120, license: 'NYC-REST-094218', specialization: 'Omakase & Premium Sushi',   address: '480 Court St, Brooklyn, NY',      phone: '+1 (718) 555-3009', email: 'reserve@noriandco.com',         avail: 'Reservations open', insurance: [], specializations: ['Sushi', 'Omakase', 'Japanese', 'Sake'], img: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=300&h=300&q=80&auto=format&fit=crop', hero: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80&auto=format&fit=crop', bio: 'Nori & Co. is Brooklyn\'s premier omakase experience — a ten-seat counter where Chef Kenji Mori presents 18 courses of meticulously sourced, expertly prepared sushi and sashimi. The fish is flown in from Tsukiji three times a week. The sake programme is exceptional. Reservations open 30 days in advance and sell out within hours.', services: ['Omakase Menu', 'À La Carte Sushi', 'Sake Pairing', 'Private Dining', 'Chef\'s Counter', 'Gift Experiences', 'Corporate Bookings'], certifications: ['NYC Health Dept A Rating', 'Michelin Star 2023 & 2024', 'New York Times 3 Stars', 'Eater NY Best Sushi 2024'] },
  ],
};

const SAMPLE_REVIEWS = [
  { id: 1, rating: 5, name: 'Sarah M.', date: 'March 2025', text: 'Absolutely incredible. Professional, warm, and the quality exceeded every expectation. I\'ve already recommended them to three friends.' },
  { id: 2, rating: 5, name: 'James T.', date: 'February 2025', text: 'Best experience I\'ve had. Everything was explained clearly, no surprises, and I felt genuinely taken care of throughout.' },
  { id: 3, rating: 4, name: 'Priya K.', date: 'January 2025', text: 'Very professional and thorough. Wait time was a touch longer than expected but the quality of service more than made up for it. Will be back.' },
];

const INDUSTRY_LABEL = {
  photographers:          'Photographers',
  'salon-spa':            'Salon & Spa',
  restaurants:            'Restaurants',
  'home-services':        'Home Services',
  'professional-service': 'Professional Services',
};
const FEE_LABEL = {
  photographers:          '/ session',
  'salon-spa':            '/ session',
  restaurants:            '/ person',
  'home-services':        '/ job',
  'professional-service': '/ hour',
};
const STAT_LABEL = {
  photographers:          'Sessions',
  'salon-spa':            'Sessions',
  restaurants:            'Covers/wk',
  'home-services':        'Jobs done',
  'professional-service': 'Clients',
};

const BackBar = ({ label, onBack }) => (
  <div style={{
    background: 'var(--bg)', borderBottom: '1px solid var(--line-2)',
    padding: '0 32px', height: 44,
  }}>
    <div style={{ maxWidth: 1240, margin: '0 auto', display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: '100%' }}>
      <button onClick={onBack} style={{
        display: 'inline-flex', alignItems: 'center', gap: 6,
        background: 'none', border: 'none', cursor: 'pointer',
        font: '500 13px/1 Inter', color: 'var(--ink-2)', padding: '4px 0',
      }}>
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M19 12H5m7-7-7 7 7 7" />
        </svg>
        Back to {label}
      </button>
      <button style={{
        display: 'inline-flex', alignItems: 'center', gap: 6,
        padding: '6px 14px', borderRadius: 8,
        border: '1px solid var(--line)', background: 'transparent',
        font: '500 13px/1 Inter', color: 'var(--ink-2)', cursor: 'pointer',
      }}>
        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
          <circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/>
          <line x1="8.59" y1="13.51" x2="15.42" y2="17.49"/><line x1="15.41" y1="6.51" x2="8.59" y2="10.49"/>
        </svg>
        Share
      </button>
    </div>
  </div>
);

const SectionHead = ({ title }) => (
  <div style={{ font: '600 15px/1 Inter', color: 'var(--ink)', marginBottom: 14, display: 'flex', alignItems: 'center', gap: 8 }}>
    <span>{title}</span>
    <div style={{ flex: 1, height: 1, background: 'var(--line-2)' }} />
  </div>
);

export default function ProProfile() {
  const { industry, id } = useParams();
  const navigate = useNavigate();
  const pros = ALL_PROS[industry] || [];
  const pro = pros.find(p => p.id === parseInt(id, 10));
  const feeLabel = FEE_LABEL[industry] || '/ session';
  const isBusiness = ['salon-spa', 'restaurants'].includes(industry);
  const displayName = isBusiness ? pro?.studio : pro?.name;

  const [form, setForm] = useState({ service: '', date: '', time: '', notes: '' });
  const [sent, setSent] = useState(false);
  const [tab, setTab] = useState('book');
  const [chat, setChat] = useState('');
  const [chatLog, setChatLog] = useState([]);
  const set = (k, v) => setForm(f => ({ ...f, [k]: v }));

  React.useEffect(() => { if (!pro) navigate(`/${industry}`, { replace: true }); }, [pro, navigate, industry]);
  if (!pro) return null;

  const sendChat = () => {
    if (!chat.trim()) return;
    setChatLog(l => [...l, { from: 'me', text: chat.trim() }]);
    setChat('');
    setTimeout(() => setChatLog(l => [...l, { from: 'them', text: isBusiness ? `Hi! This is the ${pro.studio} team. We'll get back to you shortly.` : `Hi! This is ${pro.name.split(' ')[0]}'s team. We'll get back to you shortly.` }]), 900);
  };

  const inputSt = { width: '100%', border: '1.5px solid var(--line)', borderRadius: 10, padding: '11px 13px', font: '400 13px/1.4 Inter', color: 'var(--ink)', background: 'var(--bg)', outline: 'none', boxSizing: 'border-box', transition: 'border-color .15s', fontFamily: 'Inter, sans-serif' };
  const fo = e => { e.target.style.borderColor = 'var(--accent)'; };
  const fb = e => { e.target.style.borderColor = 'var(--line)'; };
  const labelSt = { display: 'block', font: '500 12px/1 Inter', color: 'var(--ink-2)', marginBottom: 5 };
  const canSubmit = form.service && form.date;

  return (
    <div style={{ background: 'var(--bg)', minHeight: '100vh' }}>
      <SiteNav />
      <BackBar label={INDUSTRY_LABEL[industry] || industry} onBack={() => navigate(`/${industry}`)} />

      {/* Hero */}
      <div style={{ width: '100%', height: 260, overflow: 'hidden', position: 'relative' }}>
        <img src={pro.hero} alt={pro.studio} style={{ width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center 40%' }} />
        <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to bottom, transparent 40%, rgba(10,8,6,0.55) 100%)' }} />
      </div>

      {/* Profile header */}
      <div style={{ background: 'var(--bg)', borderBottom: '1px solid var(--line-2)' }}>
        <div style={{ maxWidth: 1240, margin: '0 auto', padding: '16px 32px 28px' }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 24, flexWrap: 'wrap' }}>
            <div style={{ display: 'flex', alignItems: 'flex-start', gap: 20 }}>
              {isBusiness ? (
                /* Business / brand avatar — square with rounded corners */
                <div style={{ width: 100, height: 100, borderRadius: 20, border: '4px solid white', boxShadow: '0 4px 20px -4px rgba(20,15,10,0.3)', overflow: 'hidden', flexShrink: 0, background: 'var(--bg-alt)', marginTop: -50, position: 'relative', zIndex: 2 }}>
                  <img src={pro.img} alt={pro.studio} style={{ width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center center' }} />
                </div>
              ) : (
                /* Individual / person avatar — circle */
                <div style={{ width: 112, height: 112, borderRadius: '50%', border: '4px solid white', boxShadow: '0 4px 20px -4px rgba(20,15,10,0.3)', overflow: 'hidden', flexShrink: 0, background: 'var(--bg-alt)', marginTop: -56, position: 'relative', zIndex: 2 }}>
                  <img src={pro.img} alt={pro.name} style={{ width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center top' }} />
                </div>
              )}
              <div style={{ paddingTop: 10 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap', marginBottom: 8 }}>
                  <h1 style={{ margin: 0, font: '700 26px/1.1 Inter', letterSpacing: '-0.02em', color: 'var(--ink)' }}>{displayName}</h1>
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-label="Verified">
                    <circle cx="12" cy="12" r="12" fill="var(--green)" />
                    <path d="M7 12.5l3.5 3.5 6.5-7" stroke="#fff" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </div>
                {isBusiness ? (
                  <div style={{ font: '400 14px/1.4 Inter', color: 'var(--ink-2)', marginBottom: 10 }}>{pro.specialization}</div>
                ) : (
                  <div style={{ font: '400 14px/1.4 Inter', color: 'var(--ink-2)', marginBottom: 10 }}>{pro.title} · {pro.specialization}</div>
                )}
                <div style={{ display: 'flex', alignItems: 'center', gap: 18, font: '400 13px/1 Inter', color: 'var(--ink-3)', flexWrap: 'wrap' }}>
                  <span style={{ display: 'flex', alignItems: 'center', gap: 5 }}><Icon name="pin" size={13} color="var(--accent)" />{pro.address}</span>
                  {pro.experience > 0 && <span style={{ display: 'flex', alignItems: 'center', gap: 5 }}><Icon name="briefcase" size={13} color="var(--ink-3)" />{pro.experience}+ yrs experience</span>}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Body */}
      <div style={{ maxWidth: 1240, margin: '0 auto', padding: '36px 32px 80px', display: 'grid', gridTemplateColumns: '1fr 360px', gap: 36, alignItems: 'start' }}>

        {/* Left */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 32 }}>
          <section>
            <SectionHead title="About" />
            <p style={{ font: '400 14px/1.75 Inter', color: 'var(--ink-2)', margin: 0 }}>{pro.bio}</p>
          </section>

          <section>
            <SectionHead title="Specializations" />
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
              {(pro.specializations || []).map(tag => (
                <span key={tag} style={{ padding: '7px 14px', borderRadius: 999, background: 'var(--accent-soft)', border: '1px solid oklch(0.88 0.08 30)', font: '500 13px/1 Inter', color: 'var(--accent)' }}>{tag}</span>
              ))}
            </div>
          </section>

          <section>
            <SectionHead title="Certification" />
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {pro.certifications.map((cert, i) => (
                <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '10px 14px', background: 'var(--bg-alt)', borderRadius: 10, border: '1px solid var(--line-2)' }}>
                  <div style={{ width: 28, height: 28, borderRadius: 8, background: 'var(--accent-soft)', display: 'grid', placeItems: 'center', flexShrink: 0 }}>
                    <Icon name="check-badge" size={14} color="var(--accent)" />
                  </div>
                  <span style={{ font: '500 13px/1.3 Inter', color: 'var(--ink-2)' }}>{cert}</span>
                </div>
              ))}
            </div>
          </section>


          <section>
            <SectionHead title="Reviews" />
            <div style={{ display: 'flex', alignItems: 'center', gap: 16, marginBottom: 18, padding: '16px 18px', background: 'var(--bg-alt)', borderRadius: 12, border: '1px solid var(--line-2)' }}>
              <div style={{ textAlign: 'center' }}>
                <div style={{ font: '700 36px/1 Inter', color: 'var(--ink)', letterSpacing: '-0.03em' }}>{pro.rating}</div>
                <div style={{ display: 'flex', gap: 2, marginTop: 6, justifyContent: 'center' }}>
                  {[1,2,3,4,5].map(i => <Icon key={i} name="star" size={14} color={i <= Math.round(pro.rating) ? 'oklch(0.72 0.14 75)' : 'var(--line)'} />)}
                </div>
                <div style={{ font: '400 11px/1 Inter', color: 'var(--ink-3)', marginTop: 5 }}>{pro.reviews} reviews</div>
              </div>
              <div style={{ flex: 1, height: 1, background: 'var(--line-2)' }} />
              <div style={{ display: 'flex', flexDirection: 'column', gap: 5, flex: 2 }}>
                {[5,4,3].map(star => (
                  <div key={star} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <span style={{ font: '400 12px/1 Inter', color: 'var(--ink-3)', width: 8 }}>{star}</span>
                    <Icon name="star" size={11} color="oklch(0.72 0.14 75)" />
                    <div style={{ flex: 1, height: 5, borderRadius: 999, background: 'var(--line-2)', overflow: 'hidden' }}>
                      <div style={{ height: '100%', borderRadius: 999, background: 'oklch(0.72 0.14 75)', width: star === 5 ? '74%' : star === 4 ? '18%' : '8%' }} />
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              {SAMPLE_REVIEWS.map(r => (
                <div key={r.id} style={{ padding: '16px 18px', background: 'var(--bg)', border: '1px solid var(--line-2)', borderRadius: 12 }}>
                  <div style={{ display: 'flex', gap: 2, marginBottom: 8 }}>
                    {[1,2,3,4,5].map(i => <Icon key={i} name="star" size={13} color={i <= r.rating ? 'oklch(0.72 0.14 75)' : 'var(--line)'} />)}
                  </div>
                  <p style={{ font: '400 13px/1.65 Inter', color: 'var(--ink-2)', margin: '0 0 10px' }}>"{r.text}"</p>
                  <div style={{ display: 'flex', justifyContent: 'space-between', font: '500 12px/1 Inter', color: 'var(--ink-3)' }}>
                    <span>— {r.name}</span><span>{r.date}</span>
                  </div>
                </div>
              ))}
            </div>
          </section>
        </div>

        {/* Right — booking */}
        <div style={{ position: 'sticky', top: 80, display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div style={{ background: 'var(--bg)', border: '1px solid var(--line-2)', borderRadius: 16, overflow: 'hidden', boxShadow: '0 4px 24px -8px rgba(20,15,10,0.1)' }}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', borderBottom: '1px solid var(--line-2)' }}>
              {['book', 'chat'].map(t => (
                <button key={t} onClick={() => setTab(t)} style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, padding: '12px 8px', border: 'none', background: tab === t ? 'var(--bg)' : 'var(--bg-alt)', font: tab === t ? '600 13px/1 Inter' : '400 13px/1 Inter', color: tab === t ? 'var(--accent)' : 'var(--ink-3)', cursor: 'pointer', borderBottom: tab === t ? '2px solid var(--accent)' : '2px solid transparent', transition: 'all .15s' }}>
                  {t === 'book' ? 'Book / Reserve' : 'Message'}
                </button>
              ))}
            </div>
            <div style={{ padding: 20 }}>
              {tab === 'chat' ? (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
                  <div style={{ minHeight: 180, maxHeight: 220, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 10, marginBottom: 12, padding: '4px 0' }}>
                    {chatLog.length === 0 && (
                      <div style={{ textAlign: 'center', color: 'var(--ink-3)', font: '400 12px/1.6 Inter', padding: '24px 12px' }}>
                        Send a message to start a conversation with {displayName}.
                      </div>
                    )}
                    {chatLog.map((m, i) => (
                      <div key={i} style={{ display: 'flex', justifyContent: m.from === 'me' ? 'flex-end' : 'flex-start' }}>
                        <div style={{ maxWidth: '80%', padding: '8px 12px', borderRadius: m.from === 'me' ? '12px 12px 4px 12px' : '12px 12px 12px 4px', background: m.from === 'me' ? 'var(--accent)' : 'var(--bg-alt)', color: m.from === 'me' ? 'white' : 'var(--ink-2)', font: '400 12px/1.5 Inter', border: m.from === 'me' ? 'none' : '1px solid var(--line-2)' }}>
                          {m.text}
                        </div>
                      </div>
                    ))}
                  </div>
                  <div style={{ display: 'flex', gap: 8 }}>
                    <input value={chat} onChange={e => setChat(e.target.value)} onKeyDown={e => e.key === 'Enter' && sendChat()} placeholder="Type a message…" style={{ flex: 1, border: '1.5px solid var(--line)', borderRadius: 10, padding: '9px 13px', font: '400 13px/1 Inter', color: 'var(--ink)', background: 'var(--bg)', outline: 'none' }} />
                    <button onClick={sendChat} style={{ padding: '9px 16px', borderRadius: 10, border: 'none', background: 'var(--accent)', color: 'white', font: '600 13px/1 Inter', cursor: 'pointer' }}>Send</button>
                  </div>
                </div>
              ) : sent ? (
                <div style={{ textAlign: 'center', padding: '24px 0' }}>
                  <div style={{ width: 48, height: 48, borderRadius: '50%', background: 'oklch(0.94 0.06 145)', display: 'grid', placeItems: 'center', margin: '0 auto 14px' }}>
                    <Icon name="check-badge" size={24} color="var(--green)" />
                  </div>
                  <div style={{ font: '600 16px/1.2 Inter', color: 'var(--ink)', marginBottom: 6 }}>Request sent!</div>
                  <div style={{ font: '400 13px/1.5 Inter', color: 'var(--ink-3)', marginBottom: 16 }}>{displayName} will respond within 1 hour.</div>
                  <button onClick={() => setSent(false)} style={{ font: '500 12px/1 Inter', color: 'var(--accent)', background: 'none', border: 'none', cursor: 'pointer' }}>Send another request</button>
                </div>
              ) : (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
                  <div style={{ background: 'var(--accent-soft)', border: '1px solid oklch(0.88 0.08 30)', borderRadius: 10, padding: '10px 14px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span style={{ font: '500 13px/1 Inter', color: 'var(--ink-2)' }}>Starting from</span>
                    <span style={{ font: '700 18px/1 Inter', color: 'var(--accent)', letterSpacing: '-0.02em' }}>${pro.fee} <span style={{ font: '400 11px/1 Inter', color: 'var(--ink-3)' }}>{feeLabel}</span></span>
                  </div>
                  <div>
                    <label style={labelSt}>Service *</label>
                    <div style={{ position: 'relative' }}>
                      <select value={form.service} onChange={e => set('service', e.target.value)} style={{ ...inputSt, paddingRight: 34, cursor: 'pointer', appearance: 'none', WebkitAppearance: 'none' }} onFocus={fo} onBlur={fb}>
                        <option value="">Select a service…</option>
                        {pro.services.map(s => <option key={s}>{s}</option>)}
                      </select>
                      <div style={{ position: 'absolute', right: 10, top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none' }}>
                        <Icon name="chevron-down" size={13} color="var(--ink-3)" />
                      </div>
                    </div>
                  </div>
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
                    <div>
                      <label style={labelSt}>Preferred Date *</label>
                      <input type="date" value={form.date} onChange={e => set('date', e.target.value)} style={inputSt} onFocus={fo} onBlur={fb} />
                    </div>
                    <div>
                      <label style={labelSt}>Preferred Time</label>
                      <input type="time" value={form.time} onChange={e => set('time', e.target.value)} style={inputSt} onFocus={fo} onBlur={fb} />
                    </div>
                  </div>
                  <div>
                    <label style={labelSt}>Notes</label>
                    <textarea rows={3} value={form.notes} onChange={e => set('notes', e.target.value)} placeholder="Any details or special requests…" style={{ ...inputSt, resize: 'vertical', minHeight: 72 }} onFocus={fo} onBlur={fb} />
                  </div>
                  <button onClick={() => { if (canSubmit) setSent(true); }} style={{ width: '100%', padding: '13px', borderRadius: 11, border: 'none', background: canSubmit ? 'var(--accent)' : 'oklch(0.88 0.01 80)', color: canSubmit ? 'white' : 'var(--ink-3)', font: '600 14px/1 Inter', cursor: canSubmit ? 'pointer' : 'default', transition: 'opacity .15s, background .2s' }}>
                    Request Booking
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
      <SiteFooter />
    </div>
  );
}
